#ifndef ANSI_COLOR_H
#define ANSI_COLOR_H

#define NONE "\e[0m"
#define BLACK "\e[0;30m"
#define BOLD_BLACK "\e[1;30m"
#define RED "\e[0;31m"
#define BOLD_RED "\e[1;31m"
#define GREEN "\e[0;32m"
#define BOLD_GREEN "\e[1;32m"
#define BROWN "\e[0;33m"
#define YELLOW "\e[1;33m"
#define BLUE "\e[0;34m"
#define BOLD_BLUE "\e[1;34m"
#define PURPLE "\e[0;35m"
#define BOLD_PURPLE "\e[1;35m"
#define CYAN "\e[0;36m"
#define BOLD_CYAN "\e[1;36m"
#define GRAY "\e[0;37m"
#define WHITE "\e[1;37m"

#define BOLD "\e[1m"
#define UNDERLINE "\e[4m"
#define BLINK "\e[5m"
#define REVERSE "\e[7m"
#define HIDE "\e[8m"
#define CLEAR "\e[2J"
#define CLRLINE "\r\e[K"
#define CLRAFTER "\e[K"
#define MOVE_UP(n) "\e[" #n "A"
#define MOVE_DOWN(n) "\e[" #n "B"
#define MOVE_RIGHT(n) "\e[" #n "C"
#define MOVE_LEFT(n) "\e[" #n "D"
#endif /*ANSI_COLOR_H*/
